name: Verify Schema Update

on:
  workflow_call:
  workflow_run:
    workflows: ["Verify Database"]
    types:
      - completed

defaults:
  run:
    working-directory: ./server

env:
  DATABASE_URL: postgresql://postgres:password@localhost:5433/comic_book_store_db?schema=public

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: execute flyway in docker 🐳
        run: docker compose up -d
      - name: Server Install
        run: npm i
      - name: Prisma Pull
        run: npm run prisma:pull
      - name: Prisma Generate
        run: npm run prisma:generate
      - name: Debug Git Status
        run: git status
      - name: Check for modified snapshots / database schema
        id: snapshot-check
        run: echo ::set-output name=modified::$(if git status | grep "nothing to commit"; then echo "false"; else echo "true"; fi)
      - name: Debug Snapshot Check
        run: echo ${{ steps.snapshot-check.outputs.modified }}
      - name: Commit any updated snapshots / database schema changes
        if: steps.snapshot-check.outputs.modified == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Commit for snapshot update
      - name: Spin Down Docker 🐳
        run: docker compose down
